### ISSUE TITLE
The latest release available via pip is 0.3.5

### ISSUE THREAD

**Issue by dobrynski** [doubleO8/enigma2_http_api#2]
Hi,

The latest release available via pip is 0.3.5:
https://pypi.python.org/pypi/enigma2_http_api/

Is this intentional?
Thanks in advance.

Regards,
Michal

**Comment by doubleO8** [comment]
Absolutely. I have not published more recent releases to PyPI.
Releases after 0.3.5 contain breaking changes and I am not satisfied enough with the current implementation to publish it.
